// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IServerLogger is an autogenerated mock type for the IServerLogger type
type IServerLogger struct {
	mock.Mock
}

// Error provides a mock function with given fields: msg, attrs
func (_m *IServerLogger) Error(msg string, attrs ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, attrs...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: msg, attrs
func (_m *IServerLogger) Info(msg string, attrs ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, attrs...)
	_m.Called(_ca...)
}

// NewIServerLogger creates a new instance of IServerLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIServerLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *IServerLogger {
	mock := &IServerLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
