[app]
env = "prod" # dev | prod
debug = true
storage = "memory" # memory | sql

[server]
host = ""
port = 8888

[logger]
level = "debug" # debug | info | warn | error
channel = "stdout" # stdout | stderr | file
file = "logs/calendar.log"

[database]
host = "postgres"
port = 5432
database = "calendar"
username = "calendar"
password = "calendar-pwd"
schema = "public"
