services:
  pg:
    image: postgres:17
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar-pwd
      POSTGRES_DB: calendar
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_EXPOSE_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: